- name: Install tools
  become: yes
  pacman:
    name:
      - ansible
      - aria2
      - bitwarden-cli
      - github-cli
      - glances
      - jq
      - mpv
      - translate-shell
      - tree
      - unrar
      - unzip
      - wireguard-tools
      - youtube-dl
      - zathura
      - zathura-pdf-mupdf
    state: present
