---

dotfiles_repo: "https://github.com/khuedoan/dotfiles.git"

wallpaper_url: "https://free4kwallpapers.com/uploads/wallpaper/atom-one-dark-triangles-wallpaper-1920x1080-wallpaper.jpg"
wallpaper_path: "{{ ansible_env.HOME }}/Pictures/Wallpapers/Waterfall.jpg"

aur_helper: trizen

essential_packages:
  official:
    - alsa-utils
    - arandr
    - autorandr
    - bc
    - bspwm
    - dunst
    - feh
    - firefox
    - fzf
    - git
    - libnotify
    - light
    - maim
    - npm
    - playerctl
    - sxhkd
    - translate-shell
    - ttf-dejavu
    - wmctrl
    - xautolock
    - xcape
    - xclip
    - xdotool
    - xorg-server
    - xorg-setxkbmap
    - xorg-xinit
    - xorg-xrandr
    - xorg-xsetroot
    - xss-lock
  aur:
    - compton-tryone-git
    - nerd-fonts-source-code-pro
    - polybar
  custom:
    - dmenu
    - slock
    - st

extra_packages:
  official:
    - arc-gtk-theme
    - aria2
    - glances
    - gvfs
    - htop
    - man
    - mpv
    - noto-fonts
    - noto-fonts-cjk
    - noto-fonts-emoji
    - noto-fonts-extra
    - ntfs-3g
    - papirus-icon-theme
    - pcmanfm-gtk3
    - pdfjs
    - ranger
    - tmux
    - tree
    - unrar
    - unzip
    - w3m
    - xarchiver
    - youtube-dl
    - zathura
    - zathura-pdf-mupdf
    - zip
  aur:
    - ttf-ms-fonts
    - ibus-bamboo
